kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ncea-enricher-fileshare-sc
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: {{ .Values.pv.storageAccountResourceGroup }}
  storageAccount: {{ .Values.pv.storageAccountName }}
  server: {{ .Values.pv.storageAccountFilePrivateEndpointFqdn }} 
  shareName: {{ .Values.pv.enrichedMetadataShareName }}  
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - cache=strict  # https://linux.die.net/man/8/mount.cifs
 - nosharesock  # reduce probability of reconnect race
 - actimeo=30  # reduce latency for metadata-heavy workload