replicaCount: 1

image:
  repository: nceapocsbox.azurecr.io/defra/ncea-enricher-service
  pullPolicy: IfNotPresent
  tag: 20240304.19_feature-310857-Enricher-Boilerplate

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: serviceaccount-nceaenricher-sbox

env:
  serviceBusHostName: DEVNCESBINF1401.servicebus.windows.net
  keyVaultUri: https://devnceinfkvt1401.vault.azure.net/
  blobStorageUri: https://devnceinfst1401.blob.core.windows.net
  classifierApiBaseUri: https://dev-ncea-classifier.azure.defra.cloud/
  microsoftMlResourcePath: "/metadata-import/WordVectors"

podAnnotations: {}

podLabels: 
  azure.workload.identity/use: "true"

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


volumes: 
- mountPath: /metadata-import
  name: enrichedmetadata

volumeMounts: 
- name: enrichedmetadata
  persistentVolumeClaim:
    claimName: ncea-enricher-fileshare-pvc

nodeSelector: {}

tolerations: []

affinity: {}

pv:
  storageAccountResourceGroup: $(storageAccountResourceGroup)
  storageAccountName: $(storageAccountName)
  storageAccountFilePrivateEndpointFqdn: $(storageAccountFilePrivateEndpointFqdn)
  enrichedMetadataShareName: metadata-import
  pvcSize: 10Gi