replicaCount: 1

image:
  repository: $(containerRepositoryFullPath)
  pullPolicy: IfNotPresent
  tag: $(imageTag)

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: $(serviceAccountEnricher)

env:
  serviceBusHostName: $(serviceBusHostName)
  keyVaultUri: $(keyVaultUri)
  blobStorageUri: $(blobStorageUri)
  classifierApiBaseUri: $(classifierApiBaseUri)
  microsoftMlResourcePath: "/metadata-import"

podAnnotations: {}
podLabels: 
  azure.workload.identity/use: "true"

podSecurityContext: {}

securityContext: {}

#resources: {}
resources:
  requests:
    memory: "8Gi"
    cpu: "4"
  limits:
    memory: "12Gi"
    cpu: "8"

autoscaling:
  enabled: $(autoScalingEnabled)
  minReplicas: 1
  maxReplicas: $(autoScalingMaxReplicas)
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: 
- name: enrichedmetadata
  persistentVolumeClaim:
    claimName: ncea-enricher-fileshare-pvc

volumeMounts: 
- mountPath: /metadata-import
  name: enrichedmetadata

nodeSelector: {}

tolerations: []

affinity: {}

pv:
  storageAccountResourceGroup: $(storageAccountResourceGroup)
  storageAccountName: $(storageAccountName)
  storageAccountFilePrivateEndpointFqdn: $(storageAccountFilePrivateEndpointFqdn)
  enrichedMetadataShareName: metadata-import
  pvcSize: 10Gi
