replicaCount: 1

image:
  repository: 
  pullPolicy: IfNotPresent
  tag: 

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: 

env:
  serviceBusHostName: 
  keyVaultUri: 
  fileShareClientUri: 
  blobStorageUri: 

podAnnotations: {}
podLabels: 
  azure.workload.identity/use: "true"

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


volumes: 
  - mountPath: /metadata-import
    name: enrichedmetadata

volumeMounts: 
  - name: enrichedmetadata
    persistentVolumeClaim:
      claimName: ncea-enricher-fileshare-pvc

nodeSelector: {}

tolerations: []

affinity: {}

pv:
  storageAccountResourceGroup: $(storageAccountResourceGroup)
  storageAccountName: $(storageAccountName)
  storageAccountFilePrivateEndpointFqdn: $(storageAccountFilePrivateEndpointFqdn)
  enrichedMetadataShareName: metadata-import
  pvcSize: 10Gi