{{- define "ncea-enricher.container" -}}
ports:
- containerPort: {{ .Values.container.port }}
volumeMounts:
- mountPath: /metadata-import
  name: enrichedmetadata  
- mountPath: /tmp
  name: temp-dir
- name: custom-root-ca
  mountPath: /etc/ssl/certs/defra-egress-firewall-cert-01.crt
  subPath: defra-egress-firewall-cert-01.crt
  readOnly: true
{{- end -}}
