{{- include "adp-helm-library.deployment" (list . "ncea-enricher.deployment") -}}
{{- define "ncea-enricher.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "ncea-enricher.container") }}
      volumes:
      - name: enrichedmetadata
        persistentVolumeClaim:
          claimName: {{ $.Values.pvc.metaDataFileShareName }}s
      - name: temp-dir
        emptyDir: {}
      - name: custom-root-ca
        secret:
          secretName: custom-ca-trust-secret
          optional: true
{{- end -}}
