apiVersion: v2
name: ncea-enricher-infra
description: An ASO Helm chart to deploy the ADP enricher Template Infrastructure
version: 0.0.1
dependencies:
- name: adp-aso-helm-library
  version: ^2.0.1-prerelease1
  repository: https://raw.githubusercontent.com/defra/adp-helm-repository/main/adp-aso-helm-library

