apiVersion: v2
description: A Helm Chart to deploy the ncea-enricher application to Kubernetes
name: ncea-enricher
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: adp-helm-library
  version: ^1.0.0
  repository: https://raw.githubusercontent.com/defra/adp-helm-repository/main/adp-helm-library
